import * as React from 'react';
import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/Theme-provider';
import { Roboto } from 'next/font/google';
import '../globals.css';

import Sidebar from '@/components/common/Sidebar';
import ProfileDetails from '@/components/common/ProfileDetails';

const roboto = Roboto({ 
	subsets: ['latin'],
	weight: '500'
});

export const metadata: Metadata = {
	title: 'Romerto Livros',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<>
			<html lang="en" suppressHydrationWarning>
				<body className={roboto.className}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>

						<div className='bg-primaryWhite dark:bg-primaryDark bg-background-white dark:bg-background-dark flex'>
							<Sidebar />
								
							<div className='flex flex-col text-black dark:text-white h-screen w-screen overflow-y-scroll overflow-x-hidden'>
								<section className='flex flex-col justify-end ml-28 mr-14'>
									<div>
										<ProfileDetails />
									</div>
									{children}
								</section>
							</div>
						</div>
            
					</ThemeProvider>
				</body>
			</html>
		</>
	);
}
