import * as React from 'react';
import type { Metadata } from 'next';

import Sidebar from '@/components/common/Sidebar';
import { ProfileDetails } from '@/components/common/ProfileDetails';

export const metadata: Metadata = {
	title: 'Romerto Livros',
	description: 'Generated by create next app',
};

export default function SidebarLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<>
			<div className='bg-primaryWhite dark:bg-primaryDark bg-background-white dark:bg-background-dark flex'>
				<Sidebar />
								
				<div className='flex flex-col text-black dark:text-white h-screen w-screen overflow-y-scroll overflow-x-hidden'>
					<section className='flex flex-col justify-end ml-28 mr-14'>
						<div>
							<ProfileDetails />
						</div>
						{children}
					</section>
				</div>
			</div>
		</>
	);
}
