import * as React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/components/Theme-provider';
import './globals.css';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Romerto Livros',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<>
			<html lang="en" suppressHydrationWarning>
				<body className={inter.className}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>

						<div className='bg-primaryWhite dark:bg-primaryDark'>
							{children}
						</div>
            
					</ThemeProvider>
				</body>
			</html>
		</>
	);
}
